const API_ENDPOINTS = {
  MENU: '/menu',
  HOME: '/',
  DOWNLOAD: '/download',
  USER_LOGIN: '/dang-nhap',
  PHONE_LOGIN: '/phone_login',
  USER_OTP: '/user-otp',
  USER_OTP_SUBMIT: '/user-otp',
  GOOGLE_LOGIN: '/google_login',
  USER_POST_LOGIN: '/dang-nhap',
  USER_POST_REGISTER: '/dang-ki',
  STORE_LIST: '/he-thong-cua-hang',
  AUTHOR_DETAIL: '/tac-gia/{slug}',
  SEARCH_POINT: '/tra-cuu-diem',
  POST_SEARCH_POINT: '/tra-cuu-diem',
  MISA_CALLBACK: '/misa/callback',
  NHANH_WEBHOOKS: '/nhanh/webhooks',
  NHANH_GET_WEBHOOKS: '/nhanh/webhooks',
  SEARCH: '/search',
  CHECKOUT_SUCCESS: '/checkout_success',
  CART_INDEX: '/cart',
  CHECKOUT_INDEX: '/checkout',
  BLOG_INDEX: '/blog',
  BLOG_DETAIL: '/blog',
  NEWEST_PRODUCT: '/san-pham-moi',
  BLOG_DETAIL_AMP: '/amp/blog/{slug}',
  CATEGORY_PAGE: '/{cateSlug}/page/{page}',
  CATEGORY_AND_POST: '/{slug}',
  GE_TAG_DETAIL: '/tags/{slug}',
  PRODUCT_DETAIL: '/{cateSlug}/{slug}',
  GET_COUPON: '/get-coupon',
  CART: '/cart',
  ADD_TO_CART: '/add-to-cart',
};

export default API_ENDPOINTS;
